services:
  - type: web
    name: digitalteam-portfolio
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/services

# Using external Supabase database - no Render database needed