services:
  - type: web
    name: digitalteam-portfolio
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: digitalteam-db
          property: connectionString

databases:
  - name: digitalteam-db
    databaseName: digitalteam
    user: digitalteam